#!/bin/bash
#Resizes the currently focused window so that it covers the entire screen

res=`xrandr 2> /dev/null | grep '*' | sed -r 's/^ +([0-9]+)x([0-9]+).+$/\1 \2/g'`
xdotool getactivewindow windowmove 0 0 windowsize $res

